apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: argocd-letsencrypt
spec:
  acme:
    email: <you email>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: argocd-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  secretName: argocd-cert
  dnsNames:
    - argo.com ##change accroding to yours
  issuerRef:
    name: argocd-letsencrypt
    kind: ClusterIssuer
